controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    # Controladores a cargar por el Controller Manager
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    my_robot_controller:
      type: jaeger_model/MyRobotController


# Parámetros de tu controlador
my_robot_controller:
  ros__parameters:
    # type: jaeger_model/MyRobotController

    joints:
      - x_joint
      - y_joint

    command_interfaces:
      - digital
    
    state_interfaces:
      - position
    
    # kp_rho: 3.0
    # kd_vx: 7.0
    kp_rho: 3.0
    kd_vx: 7.0
    # kp_yaw: 0.05
    # kd_yaw: 0.7
    kp_yaw: 0.3
    kd_yaw: 0.7
    pos_deadband: 0.1
    yaw_deadband: 0.09
    vel_deadband: 0.01
    min_cos_for_surge: 0.0
    pwm_hz: 12.0
    duty_slew_rate: 0.20

    # odom_topic: "odometry/filtered"        # donde publicas la odometría
    # setpoint_topic: "position_setpoint"    # (opcional) si enviarás consignas X/Y por tópico
    # state_joints: [x_joint, y_joint]
    # valve_names: ["valve1","valve2","valve3","valve4"]
    # deadband: 0.1


